POST http://localhost:5000/account/login
Content-Type: application/json

{
  "email": "matteoamedeo@outlook.it",
  "password": "admin"
}

###

GET  http://localhost:5000/user/dashboard
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdHRlb0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQiLCJpYXQiOjE3MDAzOTY4MTYsImV4cCI6MTcwMDQ4MzIxNn0.urhlkvYiOZHPHl3s12rn-9_U73KRoTz0UvW6UAMGcUs4ou-NDxwtrijKHSjY3wIApGH2kWfkpQXKmoL7gFaWSHbw2YCgkV8dEb9olHisJ3kOHPaYHep2Ggo2Za6_6VV7npA_sYcTA0lL7l_Djws27z3v1yhf2nbvqj24EtyV3IcwzWUYDr8O1p_WeRVtfJ1ehrUG-QhWt01hVYKL3KRa8FxyyvA401hYn00tYFCnI6P8u5DwbMjNDmzY_AGmzBkbvcsvou4APR1ILV7HAK6L7MZsV4LSw6XCjpykn1lAefn0GctUJD8drvRz1hCDasXlwQOSBn8RxBY-iJPVSsFReQ
Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdHRlb2FtZWRlb0BvdXRsb29rLml0IiwicGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTcwMDUwNDMwOSwiZXhwIjoxNzAwNTA0MzY5fQ.mwh3SrkpdoZM5SBWpNtipWZBg4n_GXznUZ5fXC_ywM7IpSXoj-GX-SLkXc3sELufXXs8CqjFokUXcBy-grPWonk7kw8sCHkfj2uueiAq4dS1V5H8iOcRppnTmC_Cl4Vwq7ZtXvl_YH0pvwF_I43tZU7-7gMfbPpMSXG_iqmNT_sV-IyiCP7Fh5soU6evz1e19Owy4yQoc83fLro0GjQ-kNeHdWR-QWme7ISOv01kit6N74t8Pz-jzPoiVU1UqSEWDN5Eb4hsRmGiFqh_S7Ft7eBpbFw3GUQSAGDm8yBIBD7QkDksKP1St2fdCFZvL_JW7n4m2JPEFyCUDxumZ8fRyQ

###

POST  http://localhost:5000/account/logout
Content-Type: application/json
Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdHRlb2FtZWRlb0BvdXRsb29rLml0IiwicGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTcwMTEwNTQxNCwiZXhwIjoxNzAxMTkxODE0fQ.RIRrR5MHgkHyyFfh9_AdmWNO3Rxk0OsCmU6S6CML1o1rmcVfISoUkftK_ueR1FJ4Ftuq1WPJq__lZc_pq1_q2YT0Gs73gAnUkNxjMPeplXlrjGrsxGicDgS0lV-XqmqQYUrTdTI_OO9HkRzHQ7yO6-JHMXCsb_SAin2KIomOoGm6h6L-Daj6-Eai_ABcg6P7CdqmZQtZgUGlpMQevMJVDcPmJYGLXYsfwySo5QsYQcdg1zBoX4M6CHVPLXGe8DIXT8YbK2-8qhAYM3rXQqRMVvU5CUzcYjSWCxjHGa1Un0zS8fc0PmekKzNAYyE98A5gB0K3pfUala_adyITyh4CwA

###

POST  http://localhost:5000/account/checkToken
Content-Type: application/json
Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdHRlb2FtZWRlb0BvdXRsb29rLml0IiwicGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTcwMTEwNTQxNCwiZXhwIjoxNzAxMTkxODE0fQ.RIRrR5MHgkHyyFfh9_AdmWNO3Rxk0OsCmU6S6CML1o1rmcVfISoUkftK_ueR1FJ4Ftuq1WPJq__lZc_pq1_q2YT0Gs73gAnUkNxjMPeplXlrjGrsxGicDgS0lV-XqmqQYUrTdTI_OO9HkRzHQ7yO6-JHMXCsb_SAin2KIomOoGm6h6L-Daj6-Eai_ABcg6P7CdqmZQtZgUGlpMQevMJVDcPmJYGLXYsfwySo5QsYQcdg1zBoX4M6CHVPLXGe8DIXT8YbK2-8qhAYM3rXQqRMVvU5CUzcYjSWCxjHGa1Un0zS8fc0PmekKzNAYyE98A5gB0K3pfUala_adyITyh4CwA
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdHRlb0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQiLCJpYXQiOjE3MDAzOTY4MTYsImV4cCI6MTcwMDQ4MzIxNn0.urhlkvYiOZHPHl3s12rn-9_U73KRoTz0UvW6UAMGcUs4ou-NDxwtrijKHSjY3wIApGH2kWfkpQXKmoL7gFaWSHbw2YCgkV8dEb9olHisJ3kOHPaYHep2Ggo2Za6_6VV7npA_sYcTA0lL7l_Djws27z3v1yhf2nbvqj24EtyV3IcwzWUYDr8O1p_WeRVtfJ1ehrUG-QhWt01hVYKL3KRa8FxyyvA401hYn00tYFCnI6P8u5DwbMjNDmzY_AGmzBkbvcsvou4APR1ILV7HAK6L7MZsV4LSw6XCjpykn1lAefn0GctUJD8drvRz1hCDasXlwQOSBn8RxBY-iJPVSsFReQ

###

GET http://localhost:5000/api/cocktails/getAllCocktails
Content-Type: application/json

###

POST http://localhost:5000/api/cocktails/createCocktail
Content-Type: application/json
Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdHRlb2FtZWRlb0BvdXRsb29rLml0IiwicGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTcwMDUwMTA0OCwiZXhwIjoxNzAwNTg3NDQ4fQ.jQg8ERoChYy7kZF-4R8zjb_jtEyyygC30p_L0hhLyXz35a7oPp9Y401YjjmgoDt_vJ20DWS2FO6NBGzk-cqGJQUDrWH71BX4Sh5XJQJMDDvjj1Q5tupEYHLEGI_f6Dp4EPyyYLEy5_N4YIy1unAlC6fx2qFoztlM2Hj705U9NfVcz8U3s6Pim9u98gcWDtgYbMRjZLyz204O1yHiSfRZNgA6GlNPhp9PYSE9ljuPMn_RwIUPfe18DeTz0KXADeZlfIYd1QXNLc0lHNtofDkh8ll5t-IEj7v7YJUNJMAHamw4HhiTQsr48tyiCIllpTk_KR0xSnHB3Sf6mK0PHqVAgQ

{
  "name": "Cocktail Test",
  "ingredienti": "test ingredienti",
  "procedimento": "test procedimento",
  "src": "test image"
}

###

POST http://localhost:5000/account/createAccount
Content-Type: application/json

{
  "firstName": "Matteo",
  "lastName": "Amedeo",
  "email": "matteoamedeo@outlook.it",
  "password": "admin"
}